### ISSUE TITLE
Call to undefined method setRootUrl()

### ISSUE THREAD

**Issue by nittonfemton** [webignition/website-rss-feed-finder#1]
```
<?php
require('vendor/autoload.php');

$finder = new webignition\WebsiteRssFeedFinder\WebsiteRssFeedFinder();
$finder->setRootUrl('http://codinghorror.com/blog/');
?>
```

$ php find_rss.php

PHP Fatal error:  Call to undefined method webignition\WebsiteRssFeedFinder\WebsiteRssFeedFinder::setRootUrl() in /home/ubuntu/tools/find_rss.php on line 5

**Comment by webignition** [comment]
Sorry, the documentation is a little outdated there! That method has moved to the `Configuration` class.

Try :

``` php
$finder->get configuration()->setRootUrl($url);
```

**Comment by webignition** [comment]
Got autocorrected ....

``` php
$finder->getConfiguration()->setRootUrl($rootUrl);
```

**Comment by nittonfemton** [comment]
thanks!

**Comment by gonami** [comment]
```
require('vendor/autoload.php');

$finder = new webignition\WebsiteRssFeedFinder\WebsiteRssFeedFinder();

$finder->getConfiguration()->setRootUrl('http://codinghorror.com/blog/');

var_dump('rss-feeds', $finder->getRssFeedUrls());
var_dump('atom-feeds', $finder->getAtomFeedUrls());
```

PHP Catchable fatal error:  
Argument 1 passed to webignition\WebResource\WebResource::setHttpResponse()
must be an instance of GuzzleHttp\Message\ResponseInterface,
instance of Guzzle\Http\Message\Response given, called 
in /......./website-rss-feed-finder/src/webignition/WebsiteRssFeedFinder/WebsiteRssFeedFinder.php
on line 170 and defined in /............./website-rss-feed-finder/vendor/webignition/web-resource-model/src/webignition/WebResource/WebResource.php
on line 116

**Comment by webignition** [comment]
@gonami Looks like `webignition\WebResource\WebResource` has been updated to support Guzzle ~5 whereas this lib is still making use of Guzzle ~3.

I'll look into resolving that.

**Comment by webignition** [comment]
@gonami Update to v0.2.2 and all will be ok
